#!/usr/bin/env python3
"""Merge bulk paper metadata into frontend/src/data/researchPapers.json."""

from __future__ import annotations

import json
from pathlib import Path


def paper(
    *,
    title: str,
    authors: str,
    year: int,
    venue: str,
    doi: str,
    min_c: float | None = None,
    max_c: float | None = None,
    dur_min: float | None = None,
    dur_max: float | None = None,
    senses: list[str],
    materials: list[str],
    materials_skin: list[str],
    thermal_modes: list[str],
    body: list[tuple[str, str]],
    ambient: float | None = None,
    thermal_perception_measure: str = "",
    body_parts_involved: str = "",
    purpose: str = "",
    actuator: str = "",
    actuator_model: str = "",
    actuator_size: str = "",
    device_size: str = "",
    temp_range_note: str = "",
    other_actuators: list[str] | None = None,
    aux_hw: list[str] | None = None,
    heat_ctrl: str = "",
    power: str = "",
    temporal: str = "",
    other_note: str = "",
    tech_summary: str = "",
    energy: str = "",
) -> dict:
    """Build one JSON object. Use ``None`` for min/max °C or duration when not reported.

    JSON uses ``null`` (not the string ``\"N/A\"``). Missing temperature or duration bounds
    are stored as ``null`` for all four duplicate keys below.

    Convention: ``dur_min == dur_max == 0`` is treated as unknown (mapped to ``null``),
    since zero is not a meaningful study duration in this dataset.
    """
    other_actuators = other_actuators or []
    aux_hw = aux_hw or []

    if min_c is None or max_c is None:
        min_c = max_c = None
    if dur_min is None or dur_max is None:
        dur_min = dur_max = None
    elif dur_min == 0 and dur_max == 0:
        dur_min = dur_max = None

    return {
        "title": title,
        "authors": authors,
        "publicationYear": year,
        "publicationVenue": venue,
        "doi": doi,
        "url": f"https://doi.org/{doi}",
        "ambientTempC": ambient,
        "minTempC": min_c,
        "maxTempC": max_c,
        "minDurationSec": dur_min,
        "maxDurationSec": dur_max,
        "senses": senses,
        "thermalPerceptionMeasure": thermal_perception_measure,
        "thermalCuePurpose": purpose,
        "thermalTransferModes": thermal_modes,
        "mainActuatorForTemperatureSensation": actuator,
        "mainActuatorModel": actuator_model,
        "mainActuatorSize": actuator_size,
        "overallDeviceSize": device_size,
        "mainActuatorPossibleTemperatureRange": temp_range_note,
        "otherSensoryActuators": other_actuators,
        "auxiliaryHardware": aux_hw,
        "heatControlMethod": heat_ctrl,
        "powerConsumption": power,
        "temporalParameters": temporal,
        "otherNote": other_note,
        "technicalSummary": tech_summary,
        "materialsInContactWithSkin": materials_skin,
        "materials": materials,
        "bodyPartsInvolved": body_parts_involved,
        "bodySites": [{"region": r, "subregion": s} for r, s in body],
        "powerEnergyConsumption": energy,
    }


NEW = [
    paper(
        title="Coldness Presentation to Ventral Forearm using Electrical Stimulation with Elastic Gel and Anesthetic Cream",
        authors="Saito, Taiga; Hamazaki, Takumi; Kaneko, Seitaro; Kajimoto, Hiroyuki",
        year=2023,
        venue="AHs",        doi="10.1145/3582700.3582713",
        min_c=18,
        max_c=40,
        dur_min=2,
        dur_max=2,
        senses=["tactile"],
        materials=["metal", "liquids-gels"],
        materials_skin=["metal", "liquids-gels"],
        thermal_modes=["conduction"],
        body=[("arm", "forearm")],
        ambient=None,
        purpose="Present cold-like sensations on the forearm via current-controlled electrical stimulation with pain-suppression schemes.",
        actuator="Electrical stimulation (gold-coated electrode array)",
        actuator_model="61-electrode array, 100–500 μs pulses, 100 pps",
        temp_range_note="Not true temperature feedback; current varied per participant.",
        tech_summary="Electrical stimulation through gel or anesthetic cream explores stable cold-sensation presentation on the ventral forearm.",
        energy="Not reported.",
        temporal="2 s bursts at 100 pps; 27 Hz scan across electrodes.",
        other_note="Ambient temperature not reported; not temperature-based stimulation.",
    ),
    paper(
        title="DexteriSync: A Hand Thermal I/O Exoskeleton for Morphing Finger Dexterity Experience",
        authors="Shen, Ximing; Kamiyama, Youichi; Minamizawa, Kouta; Nishida, Jun",
        year=2024,
        venue="UIST",        doi="10.1145/3654777.3676422",
        min_c=5,
        max_c=40,
        dur_min=300,
        dur_max=900,
        senses=["thermal-alone", "tactile", "visual"],
        materials=["metal", "silicone-based", "liquids-gels"],
        materials_skin=["metal", "silicone-based"],
        thermal_modes=["conduction", "convection"],
        body=[("hand", "fingers")],
        ambient=25,
        purpose="Morph finger dexterity and thermal perception via liquid-cooled/heated copper tubes on thumb and index.",
        actuator="Water circulation in copper and silicone tubes with Peltier-cooled reservoir",
        actuator_model="PID water temperature; 5°C and 40°C water conditions",
        temp_range_note="Room 25±1°C; cold water 5±1.5°C; warm 40±1.5°C; skin temps reported for thumb and index.",
        other_actuators=["Tube pump", "Peltier modules", "heatsinks"],
        aux_hw=["Arduino Uno", "MAX6675", "K-type thermocouple", "Locomo board"],
        heat_ctrl="PID liquid temperature control",
        tech_summary="Wearable exoskeleton circulates temperature-controlled water to dorsal thumb and index for dexterity and thermal-perception studies.",
        energy="Peltier power not fully quantified.",
        temporal="10–15 min for stabilised skin temperature; study blocks up to ~90 min.",
    ),
    paper(
        title="Smiles Summon the Warmth of Spring: A Design Framework for Thermal-Affective Interaction based in Chinese Cí Poetry",
        authors="Feng, Feng; Bennett, Dan; Mekler, Elisa D.",
        year=2024,
        venue="DIS",        doi="10.1145/3643834.3661620",
        min_c=None,
        max_c=None,
        dur_min=None,
        dur_max=None,
        senses=["visual", "auditory", "olfactory", "tactile", "thermal-alone"],
        materials=["fabrics-textiles", "air-gas", "liquids-gels"],
        materials_skin=["fabrics-textiles"],
        thermal_modes=["conduction", "convection", "radiation"],
        body=[("wholeBody", "general")],
        ambient=None,
        purpose="Derive experiential vocabulary and design concepts for thermal-affective HCI from classical Chinese poetry.",
        actuator="N/A (theory and case studies)",
        tech_summary="Framework of experiential qualities, multisensory factors, and thermal-affect interaction directions.",
        energy="N/A",
        other_note="No wearable prototype; multisensory in concepts only.",
    ),
    paper(
        title="ThermoGrasp: Enabling Localized Thermal Feedback on Fingers for Precision Grasps in Virtual Reality",
        authors="Nasser, Arshad; Hasan, Khalad",
        year=2024,
        venue="MobileHCI",        doi="10.1145/3676526",
        min_c=20,
        max_c=30,
        dur_min=3.5,
        dur_max=3.5,
        senses=["thermal-alone", "visual"],
        materials=["metal", "ceramic"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction"],
        body=[("hand", "fingertips")],
        ambient=23.5,
        purpose="Localised fingertip Peltier feedback aligned with VR grasp patterns.",
        actuator="Peltier (TEC)",
        actuator_model="TES1-03103",
        actuator_size="10×6 mm",
        temp_range_note="±3°C/s change rate; 3.5 s on-time per trial.",
        other_actuators=[],
        aux_hw=["Arduino Mega", "L298N H-bridge", "6 V supply"],
        heat_ctrl="PWM 0–255; H-bridge polarity",
        power="Up to 400 mA at 6 V per module",
        tech_summary="Five thin Peltiers on fingertips with selective activation by grasp cardinality; two VR user studies.",
        energy="Up to ~12 W if all five modules active.",
        temporal="3.5 s stimulus; ~1.5 s to ~5.25°C delta.",
    ),
    paper(
        title="Flip-Pelt: Motor-Driven Peltier Elements for Rapid Thermal Stimulation and Congruent Pressure Feedback in Virtual Reality",
        authors="Kang, Seongjun; Kim, Gwangbin; Hwang, Seokhyun; Park, Jeongju; Elsharkawy, Ahmed Ibrahim Ahmed Mohamed; Kim, SeungJun",
        year=2024,
        venue="UIST",        doi="10.1145/3654777.3676363",
        min_c=16,
        max_c=40,
        dur_min=3,
        dur_max=20,
        senses=["thermal-alone", "tactile", "visual"],
        materials=["ceramic", "silicone-based", "metal"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction"],
        body=[("arm", "forearm"), ("hand", "palm"), ("foot", "sole")],
        ambient=None,
        purpose="Flip pre-heated or pre-cooled Peltier sides against skin for fast thermal cues plus pressure in VR.",
        actuator="Motor-flipped Peltier elements",
        actuator_model="Dual-sided Peltier with silicone barrier; ~2.0 V, 0.6 A per element",
        temp_range_note="Warm side capped at 40°C; cool side ~16–28°C at 2.0 V per paper.",
        other_actuators=["Servo motors", "elastic bands for pressure"],
        aux_hw=["Arduino Nano 33 IoT", "H-bridge motor drivers"],
        heat_ctrl="PID limiting warm side to 40°C",
        power="~1.2 W per element reported",
        tech_summary="Eight motorised flippable Peltiers deliver paired thermal and pressure cues; VR demos and recognition study.",
        energy="~9.6 W eight elements; ~51 min on 3.7 V 2200 mAh pack (paper estimate).",
        temporal="Study 1: 3 s stimulus, ≥10 s rest; Study 2: 20 s segments.",
    ),
    paper(
        title="Assessing the Influence of Visual Cues in Virtual Reality on the Spatial Perception of Physical Thermal Stimuli",
        authors="Gunther, Sebastian; Skogseide, Alexandra; Buhlmann, Robin; Muehlhaeuser, Max",
        year=2024,
        venue="CHI",        doi="10.1145/3613904.3642154",
        min_c=20,
        max_c=40,
        dur_min=10,
        dur_max=10,
        senses=["thermal-alone", "visual"],
        materials=["ceramic", "polymers-synthetics"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction"],
        body=[("hand", "hand-back"), ("arm", "forearm"), ("arm", "upper-arm"), ("torso", "shoulder")],
        ambient=None,
        purpose="Measure how VR visual heat-source location affects perceived location of eight on-body Peltiers.",
        actuator="Peltier array",
        actuator_model="CP85338",
        actuator_size="30×30 mm each, 8 units",
        temp_range_note="Heating at 3°C/s to 40°C; 10 s actuation.",
        aux_hw=["ActuBoard", "3D-printed holders", "Velcro"],
        heat_ctrl="Closed-loop to 40°C plateau",
        tech_summary="Eight spaced Peltiers on non-dominant arm and hand with matched/mismatched VR visuals.",
        energy="Not reported.",
        temporal="10 s per stimulus; 3°C/s ramp.",
    ),
    paper(
        title="Non-Contact Thermal Haptics for VR",
        authors="Wang, Yida; Chen, Yi-Chao",
        year=2023,
        venue="UbiComp/ISWC",        doi="10.1145/3594739.3610724",
        min_c=20,
        max_c=40,
        dur_min=0,
        dur_max=0,
        senses=["thermal-alone"],
        materials=["air-gas", "polymers-synthetics"],
        materials_skin=["air-gas"],
        thermal_modes=["convection"],
        body=[("hand", "general")],
        ambient=None,
        purpose="Direct heated air with ultrasonic beam steering for contactless VR thermal feedback.",
        actuator="Resistive heaters plus 40 kHz ultrasonic array",
        actuator_model="20×20 transducers; 10 Ω heater; 40°C switch threshold",
        temp_range_note="Heating circuit limited at 40°C; 2.5 W heater power.",
        aux_hw=["Arduino", "MOSFET", "NTC thermistor"],
        heat_ctrl="Threshold switching at 40°C; TDM 100 ms",
        tech_summary="Prototype combines resistive warming and phased-array airflow; no user perception study in paper.",
        energy="2.5 W heating circuit stated.",
        other_note="No empirical thermal perception measures reported.",
    ),
    paper(
        title="MCU-Based Hot Compression Belt Control System as Menstrual Cramp Reliever",
        authors="Borris, Darianne Mae S.; De Chavez, Mark Anthony D.; De Ocampo, Denise R.; Linsangan, Noel B.; De Leon, Voltaire B.; Villaverde, Jocelyn Flores; Juanatas, Roben A.",
        year=2023,
        venue="ICBET",        doi="10.1145/3620679.3620705",
        min_c=35,
        max_c=42,
        dur_min=180,
        dur_max=180,
        senses=["thermal-alone", "force"],
        materials=["fabrics-textiles", "polymers-synthetics"],
        materials_skin=["fabrics-textiles"],
        thermal_modes=["conduction"],
        body=[("torso", "abdomen"), ("torso", "back")],
        ambient=None,
        purpose="PID-controlled abdominal heating with pneumatic compression for dysmenorrhea relief.",
        actuator="Embedded resistive heaters",
        actuator_model="Four heaters; LM35 sensors; PIC microcontroller",
        temp_range_note="Low/mid/high heat bands; initial mean abdominal temp ~35.22°C cited.",
        other_actuators=["Pneumatic pump", "solenoid valves"],
        heat_ctrl="PID (Mountain Cliff algorithm) three heat levels",
        tech_summary="Belt prototype combining heat and compression; small-N pain before/after study.",
        energy="Not reported.",
        temporal="3 min heating in experiments; user-configurable timer.",
    ),
    paper(
        title="Too Hot to Handle: An Evaluation of the Effect of Thermal Visual Representation on User Grasping Interaction in Virtual Reality",
        authors="Blaga, Andreea Dalia; Frutos-Pascual, Maite; Creed, Chris; Williams, Ian",
        year=2020,
        venue="CHI",        doi="10.1145/3313831.3376554",
        min_c=15,
        max_c=30,
        dur_min=0,
        dur_max=0,
        senses=["visual"],
        materials=["polymers-synthetics"],
        materials_skin=[],
        thermal_modes=[],
        body=[("hand", "general")],
        ambient=20,
        purpose="Study how purely visual hot/cold mug contents change VR grasp aperture, location, and type.",
        actuator="None (visual-only VR)",
        tech_summary="Leap Motion captures grasps on virtual mugs with hot, cold, or empty visuals under four environment styles.",
        energy="N/A",
        other_note="No physical thermal stimulation.",
    ),
    paper(
        title="Let It Snow: Designing Snowfall Experience in VR",
        authors="Wang, Haokun; Singhal, Yatharth; Kim, Jin Ryong",
        year=2024,
        venue="IMWUT",        doi="10.1145/3659587",
        min_c=9.5,
        max_c=22,
        dur_min=1.5,
        dur_max=30,
        senses=["thermal-alone", "tactile", "visual"],
        materials=["air-gas", "metal", "fabrics-textiles"],
        materials_skin=["air-gas"],
        thermal_modes=["convection", "conduction"],
        body=[("hand", "palm"), ("hand", "fingers")],
        ambient=20,
        purpose="Combine cold airflow from Peltier packs with mid-air ultrasound tactility for snow/rain VR.",
        actuator="Six Peltier packs with water cooling and fans",
        actuator_model="Walfront B07H6LK1W7 packs",
        temp_range_note="Hand area cooled toward 10°C from 22°C in ~100 s; study temps 22, 15.5, 9.5°C.",
        other_actuators=["Ultraleap STRATOS Explore ultrasound"],
        aux_hw=["Water pumps", "radiators", "Noctua fans"],
        heat_ctrl="Voltage steps 12/8/6/4 V",
        tech_summary="Hex chamber cold air plus ultrasound patterns for flake melt vs rain splash.",
        energy="Reports ~2600 W peak budget including many Peltier plates (lab bench).",
        temporal="1.5 s and 3 s tactile motifs; 10 s threshold trials; 30 s UX blocks.",
    ),
    paper(
        title="The Effects of Avatar and Environment on Thermal Perception and Skin Temperature in Virtual Reality",
        authors="Kocur, Martin; Jackermeier, Lukas; Schwind, Valentin; Henze, Niels",
        year=2023,
        venue="CHI",        doi="10.1145/3544548.3580668",
        min_c=15,
        max_c=35,
        dur_min=300,
        dur_max=300,
        senses=["visual"],
        materials=[],
        materials_skin=[],
        thermal_modes=[],
        body=[("hand", "general")],
        ambient=None,
        purpose="Measure subjective thermal sensation and hand skin temperature under fire vs ice avatars and worlds.",
        actuator="VR visuals only (Oculus Rift)",
        tech_summary="4-condition within-subject game; continuous thermocouples; Lee VAS and Bedford comfort scales.",
        energy="N/A",
        other_note="No physical thermal actuator.",
    ),
    paper(
        title="Haptic around: multiple tactile sensations for immersive environment and interaction in virtual reality",
        authors="Han, Ping-Hsuan; Chen, Yang-Sheng; Lee, Kong-Chang; Wang, Hao-Cheng; Hsieh, Chiao-En; Hsiao, Jui-Chun; Chou, Chien-Hsing; Hung, Yi-Ping",
        year=2018,
        venue="VRST",        doi="10.1145/3281505.3281507",
        min_c=18,
        max_c=38,
        dur_min=480,
        dur_max=480,
        senses=["thermal-alone", "tactile", "visual", "auditory", "force"],
        materials=["air-gas", "liquids-gels", "metal"],
        materials_skin=["air-gas", "liquids-gels"],
        thermal_modes=["convection", "radiation"],
        body=[("wholeBody", "general"), ("hand", "general")],
        ambient=22,
        purpose="Room-scale steerable modules for radiant heat, hot air, mist cooling, and wind with VR scenes.",
        actuator="Heat lamp, heat blower, mist makers, fans",
        temp_range_note="From ~22°C room: modules shift toward ~25°C (lamp), ~38°C (blower), ~18–20°C (mist/cold stack).",
        tech_summary="Hybrid ubiquitous and controller-mounted actuators; exploratory exhibition demos plus 16-participant study.",
        energy="Up to ~1683 W aggregate peak across modules (paper).",
        temporal="~8 min per application in exploratory sessions.",
    ),
    paper(
        title="Making Thermostats Great Again: Investigating Touch-Based Thermal Sensation for Manual Control of Thermostats",
        authors="Huang, Yidong; Calvary, Gaëlle; Laurillau, Yann",
        year=2024,
        venue="AVI",        doi="10.1145/3656650.3656672",
        min_c=14,
        max_c=26,
        dur_min=0,
        dur_max=0,
        senses=["thermal-alone", "visual"],
        materials=["metal", "ceramic"],
        materials_skin=["metal", "ceramic"],
        thermal_modes=["conduction"],
        body=[("hand", "fingertips")],
        ambient=14,
        purpose="Peltier touchpad reflects setpoint temperatures while users adjust a virtual thermostat.",
        actuator="Peltier",
        actuator_model="TEC1-12706",
        temp_range_note="Touchpad 14–26°C in 0.5°C steps; room held at 14°C.",
        aux_hw=["MLX90614 skin-facing sensor", "MCP9808 fingertip sensor", "2000 W room radiator"],
        heat_ctrl="Closed-loop on touchpad temperature",
        tech_summary="Think-aloud and behavioural logging of setpoint changes with and without thermal feedback.",
        energy="Radiator 2000 W; Peltier 12 V circuit.",
    ),
    paper(
        title="Fiery Hands: Designing Thermal Glove through Thermal and Tactile Integration for Virtual Object Manipulation",
        authors="Wang, Haokun; Singhal, Yatharth; Gil, Hyunjae; Kim, Jin Ryong",
        year=2024,
        venue="UIST",        doi="10.1145/3654777.3676457",
        min_c=30,
        max_c=40,
        dur_min=5,
        dur_max=5,
        senses=["thermal-alone", "tactile", "visual", "auditory"],
        materials=["fabrics-textiles", "metal", "ceramic"],
        materials_skin=["fabrics-textiles", "ceramic"],
        thermal_modes=["conduction"],
        body=[("hand", "fingers"), ("hand", "palm")],
        ambient=None,
        purpose="Dorsal Peltiers with palmar vibrotactiles exploit thermal referral for localised VR heat.",
        actuator="Flexible Peltier",
        actuator_model="TEGWAY S017A026026",
        actuator_size="26×26×2.3 mm",
        temp_range_note="+3°C over skin baseline per study; max ΔT 64°C at 2.2 V 6 A device spec.",
        other_actuators=["ERM coin vibrotactile motors"],
        aux_hw=["Heatsinks V5619A", "Arduino UNO", "relays", "Korad supplies"],
        heat_ctrl="Open/closed voltage control to steady temperature",
        tech_summary="Three user studies on placement, 52 thermal patterns, and two VR demos with interviews.",
        energy="Up to 13.2 W per actuator at max spec; study power not isolated.",
        temporal="5 s trials in lab studies; 2 s randomised bursts in fireball demo.",
    ),
    paper(
        title="Augmenting Perceived Length of Handheld Controllers: Effects of Object Handle Properties",
        authors="Park, Chaeyong; Choi, Seungmoon",
        year=2024,
        venue="CHI",        doi="10.1145/3613904.3642251",
        min_c=20,
        max_c=25,
        dur_min=0,
        dur_max=0,
        senses=["tactile"],
        materials=["polymers-synthetics", "metal", "silicone-based"],
        materials_skin=["polymers-synthetics", "metal", "silicone-based"],
        thermal_modes=["conduction"],
        body=[("hand", "palm"), ("hand", "fingers")],
        ambient=25,
        purpose="Passive aluminium vs ABS handles alter perceived length when blindfolded (no active thermal feedback).",
        actuator="Passive handle materials",
        actuator_model="ABS vs aluminium-clad ABS",
        temp_range_note="Room 25°C; conductivity 0.2 vs 226 W/m·K",
        tech_summary="Three experiments on softness, conductivity, and texture influencing length illusion.",
        energy="N/A",
    ),
    paper(
        title="An Examination of Ultrasound Mid-air Haptics for Enhanced Material and Temperature Perception in Virtual Environments",
        authors="Villa, Steeven; Weiss, Yannick; Hirsch, Niklas; Wiethoff, Alexander",
        year=2024,
        venue="MobileHCI",        doi="10.1145/3676488",
        min_c=20,
        max_c=30,
        dur_min=5,
        dur_max=5,
        senses=["tactile", "visual"],
        materials=["air-gas"],
        materials_skin=["air-gas"],
        thermal_modes=[],
        body=[("hand", "palm")],
        ambient=26,
        purpose="Test whether ultrasound mid-air haptics shifts perceived temperature with coloured objects across material states.",
        actuator="Ultrasound mid-air haptics (no Peltier)",
        actuator_model="Ultraleap STRATOS Explore",
        temp_range_note="No real temperature change; room ~26°C stable within ~0.8°C.",
        tech_summary="30 participants; gas/liquid/solid VR objects with blue/white/red and haptics on/off.",
        energy="N/A",
        other_note="Thermoreceptors not directly stimulated; perceptual effect only.",
    ),
    paper(
        title="Mid-Air Thermo-Tactile Feedback using Ultrasound Haptic Display",
        authors="Singhal, Yatharth; Wang, Haokun; Gil, Hyunjae; Kim, Jin Ryong",
        year=2021,
        venue="VRST",        doi="10.1145/3489849.3489889",
        min_c=23,
        max_c=44,
        dur_min=7,
        dur_max=10,
        senses=["thermal-alone", "tactile", "visual", "auditory"],
        materials=["air-gas", "polymers-synthetics"],
        materials_skin=["air-gas"],
        thermal_modes=["convection"],
        body=[("hand", "palm"), ("hand", "fingers")],
        ambient=23,
        purpose="Fan-forced heated air in chamber steered by ultrasound focal point for mid-air warm cues in VR.",
        actuator="Ceramic heaters JKFTP120-250 with fans",
        actuator_model="250 W elements; 2000 RPM fans",
        temp_range_note="Chamber up to ~54°C at 120 V tests; studies use warm detection and heat-pain thresholds.",
        other_actuators=["Ultraleap STRATOS Explore"],
        aux_hw=["DS18B20 sensors", "cardboard–foil chamber", "Quest 2"],
        heat_ctrl="Autotransformer voltage steps",
        tech_summary="Exp1 staircase WDT/HPDT; Exp2 pattern ID with/without 44°C; Exp3 VR VAS immersion.",
        energy="~500 W heating elements rated.",
        temporal="7 s exposure per threshold trial.",
    ),
    paper(
        title="Somaesthetic Meditation Wearable: Exploring the Effect of Targeted Warmth Technology on Meditators' Experiences",
        authors="Ezer, Talia Sofia; Giron, Jonathan; Erel, Hadas; Zuckerman, Oren",
        year=2024,
        venue="CHI",        doi="10.1145/3613904.3642557",
        min_c=38,
        max_c=42,
        dur_min=600,
        dur_max=600,
        senses=["thermal-alone"],
        materials=["fabrics-textiles", "polymers-synthetics"],
        materials_skin=["fabrics-textiles"],
        thermal_modes=["conduction"],
        body=[("torso", "abdomen"), ("torso", "back")],
        ambient=None,
        purpose="On-body polyimide heater for lower abdomen/back during meditation sessions.",
        actuator="Polyimide heater pad",
        actuator_model="50 mm pad, 3.7 Ω, 3.7–5 V",
        temp_range_note="Operating band 38–42°C with current-limited 42°C cap.",
        aux_hw=["Arduino Uno", "MOSFET", "5500 mAh power bank"],
        heat_ctrl="Simple on/off cycling",
        tech_summary="Qualitative study with/without wearable across two 10-minute meditations.",
        energy="~6.7 W peak estimate at 5 V; duty-cycled average lower.",
        temporal="10 s on / 15 s off pattern mentioned; sessions 10 min.",
    ),
    paper(
        title="Playing Cool - Winter Weather's Influence on Location-Based Gaming",
        authors="Back, Jon; Johansson, Karin B.",
        year=2021,
        venue="CHI PLAY",        doi="10.1145/3474669",
        min_c=-7,
        max_c=5,
        dur_min=600,
        dur_max=600,
        senses=["body-general", "thermal-alone", "tactile"],
        materials=["fabrics-textiles", "air-gas"],
        materials_skin=["fabrics-textiles", "air-gas"],
        thermal_modes=["convection"],
        body=[("wholeBody", "general")],
        ambient=-7,
        purpose="Qualitative study of family outdoor GPS game in −7°C Swedish winter.",
        actuator="Environmental cold (no device)",
        tech_summary="Observations and interviews on endurance, dexterity, and phone battery issues in snow.",
        energy="Phone battery discharge in cold noted.",
        temporal="~10 min play segments before warming breaks.",
    ),
    paper(
        title="Dynamic Appearance Augmentation Method that Enables Easy Prototyping of Masks for Performance",
        authors="Masui, Motoyasu; Takegawa, Yoshinari; Hirata, Keiji",
        year=2022,
        venue="AHs",        doi="10.1145/3519391.3522751",
        min_c=30,
        max_c=40,
        dur_min=7,
        dur_max=15,
        senses=["thermal-alone", "visual", "tactile"],
        materials=["metal", "foam-cushioning"],
        materials_skin=["foam-cushioning"],
        thermal_modes=["conduction"],
        body=[("head", "forehead"), ("head", "cheek")],
        ambient=None,
        purpose="Copper tape resistive heaters warm mask zones so performers feel residual heat confirming ink colour change.",
        actuator="Copper tape resistive circuits",
        temp_range_note="Thermochromic range ~30–40°C; 35°C in ~7 s for tested sizes.",
        tech_summary="User study: 11 adults locate which facial zone heated without mirror.",
        energy="3.7 V Li-ion 3000 mAh portable supply.",
        temporal="15 s applied voltage in tests.",
    ),
    paper(
        title="ThermEarhook: Investigating Spatial Thermal Haptic Feedback on the Auricular Skin Area",
        authors="Nasser, Arshad; Zheng, Kexin; Zhu, Kening",
        year=2021,
        venue="ICMI",        doi="10.1145/3462244.3479922",
        min_c=20,
        max_c=40,
        dur_min=1.5,
        dur_max=1.5,
        senses=["thermal-alone"],
        materials=["ceramic", "metal"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction"],
        body=[("head", "ear")],
        ambient=25,
        purpose="Small Peltiers around the ear for spatial hot/cold patterns.",
        actuator="Peltier",
        actuator_model="TES1-03103",
        actuator_size="10×6×1.4 mm",
        temp_range_note="3.5°C/s; ±5.25°C in 1.5 s at full PWM.",
        aux_hw=["Arduino Mega", "L298N"],
        heat_ctrl="PWM 0–255",
        power="≤400 mA at 6 V per module",
        tech_summary="Four studies on single-point, unilateral, bilateral, and pattern evaluation (58 participants total).",
        energy="Per-module 2.4 W max electrical.",
    ),
    paper(
        title="Illusory Thermal Movement on the Forearm Using Pressure and Temperature from Water and Air",
        authors="Liu, Yuhu; Nishikawa, Satoshi; Seong, Young ah; Niiyama, Ryuma; Kuniyoshi, Yasuo",
        year=2021,
        venue="CHI",        doi="10.1145/3411764.3445777",
        min_c=25,
        max_c=42,
        dur_min=3.75,
        dur_max=3.75,
        senses=["thermal-alone", "force"],
        materials=["fabrics-textiles", "liquids-gels", "air-gas"],
        materials_skin=["fabrics-textiles", "liquids-gels"],
        thermal_modes=["conduction"],
        body=[("arm", "forearm")],
        ambient=25,
        purpose="Water-pouch temperature changes plus airbag pressure create illusory moving heat/cold on forearm.",
        actuator="Water circulation to pouches",
        actuator_model="Solenoid valves; 200 L/h pumps; three reservoir temperatures",
        temp_range_note="T0 25°C, T1 32°C, T2 42°C",
        other_actuators=["Self-inflating airbag for pressure"],
        tech_summary="12 participants trace perceived motion on tablet; 90 trials factorial.",
        energy="Not reported.",
        temporal="3.75 s stimulus duration.",
    ),
    paper(
        title="ThermalWear: Exploring Wearable On-chest Thermal Displays to Augment Voice Messages with Affect",
        authors="El Ali, Abdallah; Yang, Xingyu; Ananthanarayan, Swamy; Roeggla, Thomas; Jansen, Jack; Hartcher-O'Brien, Jess; Jansen, Kaspar; Cesar, Pablo",
        year=2020,
        venue="CHI",        doi="10.1145/3313831.3376682",
        min_c=28,
        max_c=38,
        dur_min=4,
        dur_max=10,
        senses=["thermal-alone", "auditory"],
        materials=["fabrics-textiles", "metal", "ceramic"],
        materials_skin=["fabrics-textiles"],
        thermal_modes=["conduction"],
        body=[("torso", "chest")],
        ambient=23,
        purpose="Chest-worn Peltiers deliver warm/cool pulses timed with neutral voice messages.",
        actuator="Peltier",
        actuator_model="TEC1-12706",
        temp_range_note="Warm 38°C, cool 28°C vs 32°C baseline; ROC up to 1°C/s.",
        aux_hw=["BTN8982 shield", "MAX31850 thermocouple interface", "silk-elastane garment"],
        heat_ctrl="PID rate-limited heating/cooling",
        tech_summary="Two experiments on chest comfort and on emotional interpretation of spoken content.",
        energy="Not fully reported.",
        temporal="Exp1: 7 s cues with 10 s gaps; Exp2: 4 s co-timed with audio.",
    ),
    paper(
        title="ThermOn: thermo-musical interface for an enhanced emotional experience",
        authors="Akiyama, Shimon; Sato, Katsunari; Makino, Yasutoshi; Maeno, Takashi",
        year=2013,
        venue="ISWC",        doi="10.1145/2493988.2494326",
        min_c=31,
        max_c=37,
        dur_min=6,
        dur_max=20,
        senses=["thermal-alone", "auditory"],
        materials=["ceramic", "metal"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction"],
        body=[("head", "ear")],
        ambient=26,
        purpose="Peltier headphone interface couples warming/cooling trajectories to music for affective listening.",
        actuator="Peltier",
        actuator_model="Nihon Tecmo 20×20 mm",
        temp_range_note="Baseline 34°C with ±1–3°C excursions; safe band 20–40°C.",
        aux_hw=["Arduino Nano", "TA7291P driver"],
        heat_ctrl="PD PWM control; trapezoidal thermal profiles",
        tech_summary="User tests linking faster vs slower ramps and warm vs cold with liking and comfort.",
        energy="Not reported.",
        temporal="2 s attack ramp; 4 s release; static phase tied to music.",
    ),
    paper(
        title="User Expectations and Mental Models for Communicating Emotions through Compressive and Warm Affective Garment Actuation",
        authors="Foo, Esther W.; Dunne, Lucy E.; Holschuh, Brad",
        year=2021,
        venue="IMWUT",        doi="10.1145/3448097",
        min_c=30,
        max_c=37,
        dur_min=0,
        dur_max=0,
        senses=["thermal-alone", "force"],
        materials=["fabrics-textiles", "metal"],
        materials_skin=["fabrics-textiles"],
        thermal_modes=["conduction"],
        body=[("torso", "general"), ("neck", "general"), ("arm", "general"), ("hand", "general")],
        ambient=None,
        purpose="Survey-only study of desired body sites and patterns for future warm+compression garments (SMA concept).",
        actuator="Proposed SMA Joule heating (not built)",
        tech_summary="Two crowdsourced surveys on communicating emotions with compressive and warm cues.",
        energy="N/A",
        other_note="No physical prototype evaluated.",
    ),
    paper(
        title="Douleur: Creating Pain Sensation with Chemical Stimulant to Enhance User Experience in Virtual Reality",
        authors="Jiang, Chutian; Chen, Yanjun; Fan, Mingming; Wang, Liuping; Shen, Luyao; Li, Nianlong; Sun, Wei; Zhang, Yu; Tian, Feng; Han, Teng",
        year=2021,
        venue="IMWUT",        doi="10.1145/3463527",
        min_c=15,
        max_c=40,
        dur_min=30,
        dur_max=600,
        senses=["thermal-alone", "tactile", "visual", "auditory"],
        materials=["silicone-based", "chemical", "liquids-gels"],
        materials_skin=["silicone-based", "chemical"],
        thermal_modes=["conduction"],
        body=[("wrist", "general")],
        ambient=25,
        purpose="Capsaicin microdelivery with Peltier temperature control modulates pain quality for VR safety training.",
        actuator="Peltier plus microfluidic capsaicin",
        temp_range_note="15–40°C levels; 40°C chosen for strong pain in VR study.",
        aux_hw=["RF-Nano", "TTF-103 sensor", "microneedle channel", "LiPo pack"],
        heat_ctrl="PWM to Peltier with temperature feedback",
        tech_summary="Study 1 parametric pain ratings; Study 2 VR scenarios with NRS and McGill descriptors.",
        energy="~10 W system including pump and fan; ~1.5 h at 40°C on battery.",
        temporal="30 s trials; up to 10 min exposures mentioned.",
    ),
    paper(
        title="TherModule: Wearable and Modular Thermal Feedback System based on a Wireless Platform",
        authors="Maeda, Tomosuke; Kurahashi, Tetsuo",
        year=2019,
        venue="AH",        doi="10.1145/3311823.3311826",
        min_c=7,
        max_c=52,
        dur_min=4,
        dur_max=4,
        senses=["thermal-alone", "visual"],
        materials=["metal", "ceramic"],
        materials_skin=["metal", "ceramic"],
        thermal_modes=["conduction"],
        body=[("wrist", "general"), ("arm", "forearm"), ("ankle", "general")],
        ambient=24,
        purpose="Modular WiFi-controlled dual Peltier bands for movies/AR with paired visuals.",
        actuator="Peltier",
        actuator_model="Two 20×20 mm series elements",
        temp_range_note="Surface span ~7.3–52.1°C; ~4°C/s slew; 4 s cues with 1 s pre-roll in study.",
        aux_hw=["ESP32", "Pololu BD65496MUV driver", "860 mAh LiPo"],
        heat_ctrl="PWM current control; OSC at 60 fps",
        tech_summary="SAM emotion ratings while watching water-themed clip with hot/cold cues.",
        energy="Battery-limited 1720 mA max pack current.",
        temporal="Hot time constant ~5.8 s; cool ~3.8 s.",
    ),
    paper(
        title="The Six Hug Commandments: Design and Evaluation of a Human-Sized Hugging Robot with Visual and Haptic Perception",
        authors="Block, Alexis E.; Christen, Sammy; Gassert, Roger; Hilliges, Otmar; Kuchenbecker, Katherine J.",
        year=2021,
        venue="HRI",        doi="10.1145/3434073.3444656",
        min_c=35,
        max_c=40,
        dur_min=0,
        dur_max=0,
        senses=["thermal-alone", "visual", "force", "auditory"],
        materials=["fabrics-textiles"],
        materials_skin=["fabrics-textiles"],
        thermal_modes=["conduction"],
        body=[("torso", "general"), ("arm", "general")],
        ambient=None,
        purpose="Large hugging robot uses continuous heating pads under clothing for socially warm hugs.",
        actuator="Commercial resistive heating pads",
        actuator_model="Thermophore MaxHeat Deep-Heat",
        temp_range_note="Manufacturer unspecified surface temperature; always on during hugs.",
        other_actuators=["Inflatable torso", "pressure and torque sensing", "RGB-D person detection", "speaker", "face LCD"],
        tech_summary="Field study counts positive mentions of warmth; focuses on compliance and force control.",
        energy="Pad power not specified.",
    ),
    paper(
        title="Interoceptive Interaction: An Embodied Metaphor Inspired Approach to Designing for Meditation",
        authors="Dauden Roquet, Claudia; Sas, Corina",
        year=2021,
        venue="CHI",        doi="10.1145/3411764.3445137",
        min_c=35,
        max_c=45,
        dur_min=40,
        dur_max=40,
        senses=["thermal-alone", "auditory"],
        materials=["fabrics-textiles", "metal"],
        materials_skin=["fabrics-textiles"],
        thermal_modes=["conduction"],
        body=[("torso", "chest"), ("torso", "abdomen")],
        ambient=None,
        purpose="Four nichrome pads along sternum–navel deliver timed warmth patterns tied to mindful states.",
        actuator="Nichrome wire heating pads",
        actuator_size="1.5×1.5 cm pads, ≥2 cm spacing",
        temp_range_note="Per-user calibration 35–45°C; 6 s on / 4 s off; four-step patterns.",
        aux_hw=["Arduino", "MOSFETs", "insulating tape"],
        heat_ctrl="Current-limited MOSFET PWM",
        tech_summary="Soma design exploration plus qualitative user sessions on distinguishability and comfort.",
        energy="5 V USB-class supply.",
        temporal="Full pattern ~40 s; meditation blocks 5 min.",
    ),
    paper(
        title="Frisson: Leveraging Metasomatic Interactions for Generating Aesthetic Chills",
        authors="Jain, Abhinandan; Schoeller, Felix; Zhang, Emilie; Maes, Pattie",
        year=2022,
        venue="ICMI",        doi="10.1145/3536221.3556626",
        min_c=16,
        max_c=22,
        dur_min=3,
        dur_max=3,
        senses=["thermal-alone", "visual", "auditory"],
        materials=["ceramic", "fabrics-textiles"],
        materials_skin=["ceramic", "fabrics-textiles"],
        thermal_modes=["conduction"],
        body=[("torso", "back"), ("torso", "shoulder")],
        ambient=19,
        purpose="Five sequential Peltiers along the spine deliver −3°C relative cooling during evocative video.",
        actuator="Peltier modules",
        temp_range_note="~−3°C vs skin; 1 s per site; 3 s full traverse; triggered at 30 s in 60 s clip.",
        aux_hw=["nRF52832 BC832", "MPU6050", "2S 7.4 V 500 mAh LiPo"],
        heat_ctrl="PWM drivers",
        tech_summary="Tests pattern alignment with users' prior chill experiences for emotional prosthesis concept.",
        energy="Not reported.",
        temporal="1 s dwell per element; 3 s sweep; 60 s clips.",
    ),
    paper(
        title="Influence of Electric Taste, Smell, Color, and Thermal Sensory Modalities on the Liking and Mediated Emotions of Virtual Flavor Perception",
        authors="Ranasinghe, Nimesha; James, Meetha Nesam; Gecawicz, Michael; Bland, Jonathan; Smith, David",
        year=2020,
        venue="ICMI",        doi="10.1145/3382507.3418862",
        min_c=15,
        max_c=45,
        dur_min=0,
        dur_max=0,
        senses=["thermal-alone", "olfactory", "visual", "gustatory"],
        materials=["metal", "ceramic"],
        materials_skin=["metal"],
        thermal_modes=["conduction"],
        body=[("head", "lip"), ("head", "nose")],
        ambient=None,
        purpose="Peltier near lips with smell/taste/color for virtual hot/cold beverage experiences.",
        actuator="Peltier with silver heat spreader",
        temp_range_note="Hot vs cold levels; comfortable-range safety clamp (unspecified °C).",
        aux_hw=["Micro air pump for scent", "RGB LEDs", "taste electrodes"],
        heat_ctrl="PWM intensity; motor driver polarity",
        power="~7 W thermal module driver consumption (paper)",
        tech_summary="Crossed thermal, olfactory, gustatory, and colour factors for plain-water sipping illusion.",
        energy="~7 W stated for thermal driver path.",
    ),
    paper(
        title="Heat-Nav: Using Temperature Changes as Navigation Cues",
        authors="Tewell, Jordan; Bird, Jon; Buchanan, George R.",
        year=2017,
        venue="CHI",        doi="10.1145/3025453.3025965",
        min_c=29,
        max_c=35,
        dur_min=6,
        dur_max=600,
        senses=["thermal-alone"],
        materials=["metal", "ceramic"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction", "convection"],
        body=[("arm", "forearm")],
        ambient=None,
        purpose="Three forearm TECs continuously indicate path optimality toward maze goal (29–35°C).",
        actuator="Thermoelectric coolers MCPE1-01708NCS",
        temp_range_note="Neutral 32°C baseline; ±1°C/s slew; ~6 s between 29°C and 35°C extremes.",
        aux_hw=["Arduino Mega 2560", "thermistors", "Pololu MC33926", "fans and heatsinks"],
        heat_ctrl="PID per zone; BFS updates cue each move",
        power="6 V 10 A supply",
        tech_summary="12 participants navigate 2D maze using gradual thermal feedback on ventral forearm.",
        energy="High TEC power class; exact average not reported.",
        temporal="6 s transition between warm/cool targets; task up to ~10 min.",
    ),
    paper(
        title="ThermoVR: Exploring Integrated Thermal Haptic Feedback with Head Mounted Displays",
        authors="Peiris, Roshan Lalintha; Peng, Wei; Chen, Zikun; Chan, Liwei; Minamizawa, Kouta",
        year=2017,
        venue="CHI",        doi="10.1145/3025453.3025824",
        min_c=32.6,
        max_c=38,
        dur_min=6,
        dur_max=6,
        senses=["thermal-alone", "visual"],
        materials=["ceramic", "polymers-synthetics"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction"],
        body=[("head", "forehead"), ("head", "cheek")],
        ambient=24,
        purpose="Five forehead/under-eye Peltiers deliver ±3°C/s ramps for directional and immersive VR heat/cold.",
        actuator="Peltier",
        actuator_model="2×1.5 cm modules",
        temp_range_note="±3°C from ~35.6°C mean facial baseline; 1 s ramp + 5 s hold.",
        aux_hw=["Arduino Nano", "TA7291 bridges", "three sensors per module"],
        heat_ctrl="Closed-loop PID facial control",
        tech_summary="Study 1: nine-direction cue discrimination; Study 2: presence questions in campfire/water VR.",
        energy="Not reported.",
        temporal="15 s re-adaptation between directional trials.",
    ),
    paper(
        title="Hot Under the Collar: Mapping Thermal Feedback to Dimensional Models of Emotion",
        authors="Wilson, Graham; Dobrev, Dobromir; Brewster, Stephen A.",
        year=2016,
        venue="CHI",        doi="10.1145/2858036.2858205",
        min_c=22,
        max_c=38,
        dur_min=10,
        dur_max=10,
        senses=["thermal-alone"],
        materials=["ceramic"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction"],
        body=[("hand", "palm")],
        ambient=None,
        purpose="Peltiers on palm map warming/cooling rate and magnitude to self-reported affect.",
        actuator="Peltier",
        actuator_model="2 cm² modules (USB-controlled)",
        temp_range_note="30°C baseline; ±2/4/6/8°C extents; 1 or 3°C/s ROC.",
        tech_summary="20 participants; factorial on direction, ROC, and amplitude.",
        energy="USB-powered bench setup.",
        temporal="10 s stimulus; 30 s neutral return.",
    ),
    paper(
        title="HydroRing: Supporting Mixed Reality Haptics Using Liquid Flow",
        authors="Han, Teng; Anderson, Fraser; Irani, Pourang; Grossman, Tovi",
        year=2018,
        venue="UIST",        doi="10.1145/3242587.3242667",
        min_c=15,
        max_c=42,
        dur_min=8,
        dur_max=30,
        senses=["thermal-alone", "tactile"],
        materials=["latex", "liquids-gels", "metal", "ceramic"],
        materials_skin=["latex"],
        thermal_modes=["convection", "conduction"],
        body=[("hand", "fingertips")],
        ambient=None,
        purpose="Finger latex tube mixes hot/cold reservoirs for MR; second study compares bare vs worn finger on Peltier.",
        actuator="Peristaltic liquid mixing + reference Peltier",
        temp_range_note="System 2–55°C hardware; comfort-limited 15–40°C; studies at 15–35°C and 14–42°C grids.",
        aux_hw=["MLX90614 IR temperature", "PID pump blending"],
        heat_ctrl="PID on mixed outlet temperature",
        tech_summary="Recognition accuracy for seven temperature steps; minimal thermal masking when worn passively.",
        energy="Not reported.",
        temporal="~6 s for 5°C change at outlet (paper).",
    ),
    paper(
        title="Creating Thermal Icons—A Model-Based Approach",
        authors="Singhal, Anshul; Jones, Lynette A.",
        year=2018,
        venue="ACM TAP",        doi="10.1145/3182175",
        min_c=18,
        max_c=38,
        dur_min=8,
        dur_max=30,
        senses=["thermal-alone"],
        materials=["ceramic", "metal"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction"],
        body=[("hand", "fingertips"), ("wrist", "general")],
        ambient=24,
        purpose="Model-based generation of discriminable warming/cooling temporal icons on Peltier display.",
        actuator="Thermoelectric module TE-127-1.0-2.5",
        actuator_model="TE Technology on heat sink + fan; water-cooled sink in wrist experiment",
        temp_range_note="Fingertip patterns span ~18–38°C depending on icon; wrist ΔT fixed 6°C from skin baseline.",
        aux_hw=["TC-720 controller", "LabVIEW", "thermistors"],
        heat_ctrl="Closed-loop surface temperature tracking",
        tech_summary="Absolute identification of six fingertip icons; wrist transfer test with eight shorter patterns.",
        energy="Bench instrumented supply.",
        temporal="30 s fingertip stimuli; 8 s wrist stimuli.",
    ),
    paper(
        title="Painting Inferno: Novel Heat and Stiffness Control Methods with Carbon Nanomaterial Conductive Heating Paint",
        authors="Tokuda, Yutaka; Kobayashi, Tatsuya",
        year=2024,
        venue="CHI",        doi="10.1145/3613904.3642226",
        min_c=27,
        max_c=120,
        dur_min=0,
        dur_max=0,
        senses=["thermal-alone", "tactile"],
        materials=["polymers-synthetics", "metal"],
        materials_skin=["polymers-synthetics"],
        thermal_modes=["conduction"],
        body=[("hand", "fingertips")],
        ambient=27,
        purpose="Carbon-nanomaterial painted heaters for high spatial control, demos on finger interface and variable-stiffness structures.",
        actuator="Carbo e-Therm PUR 70-350B.01 resistive paint",
        temp_range_note="Bench heating rates 1.8–109°C/s at 1–9 V; PID targets 40–100°C; finger demo to 45°C <5 V.",
        aux_hw=["Arduino Uno", "MOSFET driver", "copper electrodes"],
        heat_ctrl="PID with PWM duty on matrix pixels",
        tech_summary="Characterises silver vs carbon heaters; dot-matrix and shape-changing demos without formal user study.",
        energy="0.05–10.7 W depending on voltage and trace (paper table).",
        temporal="Sub-second to multi-second ramps depending on voltage.",
    ),
    paper(
        title="Human Perception of Social Robot's Emotional States via Facial and Thermal Expressions",
        authors="Peña, Denis; Tanaka, Fumihide",
        year=2020,
        venue="ACM THRI",        doi="10.1145/3388469",
        min_c=18,
        max_c=38,
        dur_min=7,
        dur_max=7,
        senses=["thermal-alone", "visual"],
        materials=["ceramic", "metal"],
        materials_skin=["ceramic"],
        thermal_modes=["conduction"],
        body=[("hand", "general")],
        ambient=20,
        purpose="Twelve Peltiers on robot hand execute precomputed warming/cooling trajectories paired with facial animation.",
        actuator="Peltier array",
        actuator_model="TEC-1123 closed-loop controller with IR sensing",
        temp_range_note="Neutral 27.5°C; joy ~35°C; anger ~38°C; sadness ~22°C; fear ~18–19°C; 7 s expressions.",
        tech_summary="User study crossing facial and thermal channels for emotion recognition.",
        energy="Not reported.",
        temporal="7 s trapezoid; 3 min inter-stimulus rest.",
    ),
    paper(
        title="Mouillé: Exploring Wetness Illusion on Fingertips to Enhance Immersive Experience in VR",
        authors="Han, Teng; Wang, Sirui; Wang, Sijia; Fan, Xiangmin; Liu, Jie; Tian, Feng; Fan, Mingming",
        year=2020,
        venue="CHI",        doi="10.1145/3313831.3376138",
        min_c=15,
        max_c=35,
        dur_min=0,
        dur_max=0,
        senses=["thermal-alone", "tactile", "visual"],
        materials=["ceramic", "metal"],
        materials_skin=["ceramic", "metal"],
        thermal_modes=["conduction"],
        body=[("hand", "fingertips")],
        ambient=21,
        purpose="Rapid TEC cooling with mechanical stiffness/friction cues to evoke wetness for VR wet objects.",
        actuator="Water-cooled TEC plate",
        actuator_size="38×38 mm",
        temp_range_note="Study 1: 2–15°C below fingertip baseline; Study 2: T−5/T−10/T−15°C offsets.",
        aux_hw=["Servo stiffness mechanism", "VIVE Pro", "fluid cooler"],
        heat_ctrl="TEC controller ±0.02°C",
        tech_summary="Formative wetness ratings plus VR interaction study with post-hoc scales.",
        energy="Not reported.",
        temporal="Varies by trial; fingertip re-warming between presentations.",
    ),
    paper(
        title="Chemical Haptics: Rendering Haptic Sensations via Topical Stimulants",
        authors="Lu, Jasmine; Liu, Ziwei; Brooks, Jas; Lopes, Pedro",
        year=2021,
        venue="UIST",        doi="10.1145/3472749.3474747",
        min_c=20,
        max_c=30,
        dur_min=600,
        dur_max=600,
        senses=["thermal-alone", "tactile", "visual"],
        materials=["silicone-based", "chemical", "liquids-gels"],
        materials_skin=["silicone-based", "chemical"],
        thermal_modes=["conduction"],
        body=[("head", "cheek"), ("arm", "forearm")],
        ambient=None,
        purpose="Micropump-delivered menthol and capsaicin solutions create illusory cold/heat without Peltier-level power.",
        actuator="Piezo micropump through open silicone channels",
        temp_range_note="No bulk temperature change; illusory thermal percepts via TRP agonists.",
        aux_hw=["mp6 pumps", "reservoirs 1.2 mL per channel"],
        heat_ctrl="Open-loop flow pulsing 10 ms intervals",
        power="~0.52 W pumps at full intensity (paper)",
        tech_summary="TCATA-style descriptor timelines on forearm; VR walkthrough ratings on immersion.",
        energy="~0.52 W active pumps vs 4–13 W cited for small Peltiers.",
        temporal="10 min on / 10 min off in dose study 1; ≥3 min VR scenes.",
    ),
]


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    path = root / "frontend" / "src" / "data" / "researchPapers.json"
    data: list[dict] = json.loads(path.read_text(encoding="utf-8"))
    existing_dois = {p.get("doi") for p in data if p.get("doi")}
    to_add = [p for p in NEW if p.get("doi") not in existing_dois]
    if not to_add:
        print("No new papers to append (all DOIs already present).")
        return
    next_id = max(int(p["id"]) for p in data) + 1
    for entry in to_add:
        row = {"id": str(next_id), **entry}
        data.append(row)
        next_id += 1
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Appended {len(to_add)} papers; last id {next_id - 1}")


if __name__ == "__main__":
    main()
